server:
  port: 8888


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


#mybatis:
#   mapper-locations: classpath:generator/*.xml


logging:
    level:
      com.zimug.bootlaunch: debug